### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by leaxs** [leaxs/Mahjong#2]
Général
- [x] Joueur :  nom, partie joué (seed, temps), plus haut score
- [x] Partie : sauvegarde (plateau, temps, seed, joueur)
- [x] Classement : listage des joueurs en fonction de leurs score
- [x] Path-finding : renvoie du chemin pour affichage
- [x] Jeu : retour en arrière
- [x] Jeu : hint
- [ ] ~~Jeu/generation revoir la géneration à l'aide du PF (?)~~

GUI
- [x] Joueur
![image](https://user-images.githubusercontent.com/5464630/40451340-a0379ad4-5ede-11e8-97e0-b5f55e9dcd36.png)
- [x] Classement
![image](https://user-images.githubusercontent.com/5464630/40451138-e1c26458-5edd-11e8-968d-10378258734d.png)
- [x] path-finding

Puis nettoyage de code
